#Stocks microservice section
apiVersion: apps/v1
kind: Deployment
metadata:
    name: stocks
spec:
    replicas: 1
    selector:
        matchLabels:
            app: stocks
    template:
        metadata:
            labels:
                app: stocks
        spec:
            containers:
                - name: stocks
                  image: stocks:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5004

#Stocks service section
---
apiVersion: v1
kind: Service
metadata:
    name: stocks-service
spec:
    selector:
        app: stocks
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5004
    type: LoadBalancer

#Stocks database section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dbstocks
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dbstocks
            tier: postgres
    template:
        metadata:
            labels:
                app: dbstocks
                tier: postgres
        spec:
            containers:
                - name: db-stocks
                  image: postgres:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: stocks
                      - name: POSTGRES_USER
                        value: stocks
                      - name: POSTGRES_PASSWORD
                        value: stocks

#Products microservice section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: products
spec:
    replicas: 1
    selector:
        matchLabels:
            app: products
    template:
        metadata:
            labels:
                app: products
        spec:
            containers:
                - name: products
                  image: products:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5003

#Products service section
---
apiVersion: v1
kind: Service
metadata:
    name: products-service
spec:
    selector:
        app: products-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5003
    type: LoadBalancer

#Products database section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dbproducts
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dbproducts
            tier: postgres
    template:
        metadata:
            labels:
                app: dbproducts
                tier: postgres
        spec:
            containers:
                - name: db-products
                  image: postgres:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: products
                      - name: POSTGRES_USER
                        value: products
                      - name: POSTGRES_PASSWORD
                        value: products

#Cart microservice section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cart
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cart
    template:
        metadata:
            labels:
                app: cart
        spec:
            containers:
                - name: cart
                  image: cart:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5002

#Cart service section
---
apiVersion: v1
kind: Service
metadata:
    name: cart-service
spec:
    selector:
        app: cart
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5002
    type: LoadBalancer

#Cart database section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dbcart
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dbcart
            tier: postgres
    template:
        metadata:
            labels:
                app: dbcart
                tier: postgres
        spec:
            containers:
                - name: db-cart
                  image: postgres:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: cart
                      - name: POSTGRES_USER
                        value: cart
                      - name: POSTGRES_PASSWORD
                        value: cart

#Gateway section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gateway
    template:
        metadata:
            labels:
                app: gateway
        spec:
            containers:
                - name: gateway
                  image: gateway:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5000

#Gateway service section
---
apiVersion: v1
kind: Service
metadata:
    name: gateway-service
spec:
    selector:
        app: gateway
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
    type: LoadBalancer

#Gateway database section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dbgateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dbgateway
            tier: postgres
    template:
        metadata:
            labels:
                app: dbgateway
                tier: postgres
        spec:
            containers:
                - name: db-gateway
                  image: postgres:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: gateway
                      - name: POSTGRES_USER
                        value: gateway
                      - name: POSTGRES_PASSWORD
                        value: gateway

#Client section
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: client
                  imagePullPolicy: IfNotPresent
                  image: client:latest
                  ports:
                      - containerPort: 3000

#Client service section
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: LoadBalancer
